### ISSUE TITLE
clone 工程 后报错  机型 vivo x6s A   android 5.1.1

### ISSUE THREAD

**Issue by MartinLi89** [devzwy/open_nsfw_android#10]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "frexpf" referenced by "/data/app/com.example.open_nsfw_android-2/lib/arm64/libtensorflowlite_gpu_jni.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:375)
        at java.lang.System.loadLibrary(System.java:988)
        at org.tensorflow.lite.gpu.GpuDelegate.<clinit>(GpuDelegate.java:155)
        at com.zwy.nsfw.Classifier.<init>(Classifier.java:88)
        at com.zwy.nsfw.Classifier.create(Classifier.java:81)
        at com.zwy.nsfw.api.NsfwHelper.<init>(NsfwHelper.java:37)
        at com.zwy.nsfw.api.NsfwHelper.getInstance(NsfwHelper.java:28)
        at com.example.open_nsfw_android.MainActivity.initNsfwHelper(MainActivity.kt:94)
        at com.example.open_nsfw_android.MainActivity.onCreate(MainActivity.kt:34)
        at android.app.Activity.performCreate(Activity.java:6083)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
        at android.app.ActivityThread.access$900(ActivityThread.java:175)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5418)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by devzwy** [comment]
#11
