### ISSUE TITLE
华为麦芒7  android 9.0.1

### ISSUE THREAD

**Issue by MartinLi89** [devzwy/open_nsfw_android#11]
2019-07-18 17:56:34.230 26568-26711/com.example.open_nsfw_android E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.example.open_nsfw_android, PID: 26568
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: TfLiteGpuDelegate Invoke: Delegate should run on the same thread where it was initialized.Node number 90 (TfLiteGpuDelegate) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:149)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
        at com.zwy.nsfw.Classifier.run(Classifier.java:184)
        at com.zwy.nsfw.api.NsfwHelper.scanBitmapSyn(NsfwHelper.java:53)
        at com.zwy.nsfw.api.NsfwHelper$1.run(NsfwHelper.java:68)
        at java.lang.Thread.run(Thread.java:784)

**Comment by devzwy** [comment]
Gpu加速关掉试试@MartinLi89
