### ISSUE TITLE
请问有关于python的demo嘛

### ISSUE THREAD

**Issue by CulionBEAR** [devzwy/open_nsfw_android#19]
您好，请问有python的demo嘛，我这里写了一份，但是一直提醒我出错，怎么修改也找不到问题所在
这是我写的代码：
```
import numpy
import numpy as np

import tensorflow as tf

import scipy

import cv2

import os,base64
# Load TFLite model and allocate tensors.

interpreter = tf.contrib.lite.Interpreter(model_path="./nsfw.tflite")

interpreter.allocate_tensors()

# Get input and output tensors.

input_details = interpreter.get_input_details()

output_details = interpreter.get_output_details()

#imagek = cv2.imread("C:/Users/12064/Desktop/opencv/opencv/hentai/image/1a3i8.jpg",cv2.IMREAD_UNCHANGED).astype(np.float32)
imagek=cv2.imread(r"{}".format("C:/Users/12064/Desktop/opencv/opencv/hentai/image/1a3i8.jpg")).astype(np.float32)

image = cv2.resize(imagek,(224,244))

# image_ = np.array([image.astype('float32')])

interpreter.resize_tensor_input(input_details[0]['index'], [1, 224, 224, 3])
interpreter.allocate_tensors()

print(input_details)
print(image.shape)

images=[]

images.append(image)

interpreter.set_tensor(input_details[0]['index'], images)

interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])

scipy.misc.imsave('res.jpg', output_data)
```

报错：
```
Traceback (most recent call last):
  File "E:/PycharmProjects/t.py", line 40, in <module>
    interpreter.set_tensor(input_details[0]['index'], images)
  File "E:\Python3.7\lib\site-packages\tensorflow\lite\python\interpreter.py", line 175, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
  File "E:\Python3.7\lib\site-packages\tensorflow\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py", line 136, in SetTensor
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_SetTensor(self, i, value)
ValueError: Cannot set tensor: Dimension mismatch
```
将特别感谢您的回答

**Comment by devzwy** [comment]
感谢您对项目的关注。很抱歉我对python不是很熟悉。我看您这个问题会不会是tensorflow的版本有问题。新版本的tensorflow在这个鉴黄的model中不适用，建议更换相应的tensorflow和python版本进行编译。可参考：[NSFW-Python](https://github.com/devzwy/NSFW-Python)、[yahoo-open_nsfw](https://github.com/yahoo/open_nsfw)
