### ISSUE TITLE
OpenCL library not loaded

### ISSUE THREAD

**Issue by palize** [devzwy/open_nsfw_android#33]
Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
    Falling back to OpenGL

**Comment by palize** [comment]
> Virtual machines?

Galaxy Note10+

java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
Falling back to OpenGL
TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.
Node number 90 (TfLiteGpuDelegateV2) failed to invoke.

	at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
	at org.tensorflow.lite.NativeInterpreterWrapper.d(NativeInterpreterWrapper.java:23)
	at org.tensorflow.lite.c.a(Interpreter.java:4)
	at h3.q1.invokeSuspend(NSFWHelper.kt:26)
	at dc.a.resumeWith(ContinuationImpl.kt:3)
	at rc.d0.run(DispatchedTask.kt:18)
	at uc.d.run(LimitedDispatcher.kt:2)
	at vc.j.run(Tasks.kt:1)
	at vc.a$b.run(CoroutineScheduler.kt:14)
	Suppressed: rc.b0

**Comment by devzwy** [comment]
请使用真机测试。

**Comment by palize** [comment]
> 请使用真机测试。

I use a real device like Galaxy Note10+ or Samsung S7 (android 7)

**Comment by devzwy** [comment]
<img width="2534" alt="image" src="https://user-images.githubusercontent.com/24636051/192129096-f7dcf76e-c414-4bf1-a16d-384fa3447ff8.png">
```kotlin
//        fun initHelper(
//            context: Context, //建议传入application,传入activity可能会有内存泄漏
//            modelPath: String? = null,//模型文件路径，为空时将默认从Assets下读取
//            isOpenGPU: Boolean = true, //是否开启GPU扫描加速，部分机型兼容不友好的可关闭。默认开启
//            numThreads: Int = 4 //扫描数据时内部分配的线程 默认4
//        )
```

不支持gpu加速的设备，把gpu加速关了。
```kotlin
isOpenGPU = false
```
